export const DEFAULT_IGNORE_PATTERNS = [
  '**/node_modules/**',
  '**/dist/**',
  '**/build/**',
  '**/.git/**',
  '**/.turbo/**',
  '**/.next/**',
  '**/coverage/**',
  '**/*.log',
  '**/tmp/**',
  '**/temp/**',
  '**/.cache/**',
  '**/.terraform/**',
  '**/plans/**',
  '**/public/**',
  '**/venv/**',
  '**/ios/**',
  '**/android/**',
  '**/Pods/**',
  '**/cmake-build-debug/**',
  '**/.vite/**',
]

export const DEFAULT_WHITELIST_EXTENSIONS = [
  'ts',
  'tsx',
  'js',
  'jsx',
  'mjs',
  'cjs',
  'py',
  'go',
  'c',
  'cpp',
  'h',
  'html',
  'css',
  'txt',
  'md',
  'hcl',
  'tf',
  'astro',
  'json',
  'yaml',
  'yml',
  'toml',
]

// Files to show in project structure even if they have no extension or a non-whitelisted extension.
// These are typically root-level config files that are important for understanding a project.
export const STRUCTURE_VISIBLE_FILES = [
  '.editorconfig',
  '.eslintrc',
  '.eslintrc.cjs',
  '.eslintrc.json',
  '.eslintrc.yml',
  '.gitignore',
  '.lintstagedrc',
  '.npmrc',
  '.nvmrc',
  '.prettierignore',
  '.prettierrc',
  '.prettierrc.cjs',
  '.prettierrc.mjs',
  '.prettierrc.json',
  '.prettierrc.yml',
  '.terraform-docs.yml',
  '.tflint.hcl',
  'Makefile',
  'Dockerfile',
  'docker-compose.yml',
  'docker-compose.yaml',
  'CODEOWNERS',
]
